### ISSUE TITLE
eStream allows all files to be uploaded

### ISSUE THREAD

**Issue by Fae6068123** [PlaneteStream/moodle-assignsubmission_estream#13]
Submission Types section does not work as it should. If No accepted file types is indicated, or if ONLY video files or audio files is chosen, users are automatically allowed to enter any files, including word documents, PDF, etc. 
![image](https://user-images.githubusercontent.com/59917516/168617994-aa5f369d-43c7-4607-ad29-64a7f150ba96.png)
if users choose video,
![image](https://user-images.githubusercontent.com/59917516/168618559-baf2c639-21ce-451b-b278-28148148625e.png)
users can still submit any file type, including pdf, word, etc.

**Comment by PlaneteStream** [comment]
Hi @Fae6068123,

The "accepted file types" box in Moodle is unrelated to Planet eStream and only affects files uploaded directly to Moodle with the submission type "File Submission". 

The Planet eStream plugin accepts various file types as our users sometimes wish to have students use the plugin to upload things like PDFs alongside their videos, which can be viewed in-browser, or otherwise presented as download links to the file if it's an irregular file type, for example Photoshop files. 

If you have any further questions, please let us know at support@planetestream.co.uk. Thank you!

**Comment by Fae6068123** [comment]
Verified using latest version, 2021111800, somehow, if accepted file types is left blank, user is incorrectly permitted to upload and submit any file type, rather than been restricted to video or audio files. If the accepted file type is set to video (mp4, etc), the plugin still incorrectly allows users to submit all file types, including .pdf, .doc, .dot, etc
